apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: product-create
spec:
  createingress: false
  functionref:
    functionweights: null
    name: product-management
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/product/create
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /api/product/create
